spring:
  datasource:
    # Đã đổi localhost thành postgres-db
    url: jdbc:postgresql://postgres-db:5432/dictionarydb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true